name:               "ccat3z's blog"
description:        "Student / Programmer"

url:                "//ccat3z.xyz"
author:             "ccat3z"
avatar:             "/images/c0ldcat.svg"

baseurl:            ""

markdown:           kramdown

timezone:           Asia/Shanghai

nav:
  - name:           "home"
    icon:           "home"
    href:           "/"
  - name:           "post"
    icon:           "create"
    href:           "/posts/"
  # - name:           "projects"
  #   icon:           "code"
  #   href:           "/projects/"
  # - name:           "tags"
  #   icon:           "bookmark"
  #   href:           "/tags/"
  - name:           "love"
    icon:           "favorite"
    href:           "/love/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /posts/:title/
      layout: post

projects:
  - name: Netease Music Java
    description: 网易云音乐 Java API
    link: https://github.com/c0ldcat/netease-music-java
    image: /images/netease-music.svg
  - name: Scale JPG
    description: 一步解决图片大小格式限制问题
    link: https://github.com/c0ldcat/scale-jpg
    image: /images/scale-jpg.svg
  - name: Z Uploader
    description: Group uploader, 收文件专用
    link: https://github.com/c0ldcat/z-uploader
    image: /images/z-uploader.svg
  - name: Hackwlb Server
    description: 本站开源哦
    link: https://github.com/c0ldcat/hackwlb-server
    image: /images/c0ldcat.svg
  - name: Red Music
    description: Bluetooth MP3 with Netease Music
    link: https://github.com/c0ldcat/red-music
    image: /images/red-music.svg
  - name: KR Home Protocol
    description: 点对点式智能家具协议
    link: "#"
    image: /images/kmp.svg
  - name: RopeZ
    description: 厉害的线阵LED跳绳
    link: "#"
    image: /images/rope-z.svg
  - name: Pet Camera
    description: Intel IOT 2015! 超好用的宠物智能拍照神器
    link: https://github.com/c0ldcat/Pet-Camera
    image: /images/pet-camera.svg
  - name: iTool MagicQT Box with LBox Extra
    description: 敬逝去的学习机时代
    link: https://github.com/c0ldcat/Noah-NP2300-LBox
    image: /images/lbox.svg

social:
  - service: github
    username: c0ldcat
    link: https://github.com/c0ldcat
  - service: mail
    username: firez199984@gmail.com
    link: mailto:firez199984@gmail.com

background: /images/background.png

sass:
    sass_dir:         _sass
    style:            :compressed

tag_page_layout: tag-page
tag_page_dir: tag
tag_permalink_style: pretty

paginate: 10
paginate_path: "/posts/:num"

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll/tagging

exclude:
  - ".*"
  - "Gemfile"
  - "Gemfile.lock"
  - "vendor"
  - "dist"
  - "build"
  - "Makefile"
