name:               "c0ldcat's blog"
description:        "一个伪装成菜鸡全栈工程师的上海高三狗"

url:                "//blog.c0ldcat.ml"
author:             "c0ldcat"

baseurl:            ""

markdown:           kramdown

nav:
  - name:           "文章"
    href:           "/posts"
  - name:           "项目"
    href:           "/projects"
  - name:           "标签"
    href:           "/tags"

collections:
    col_tags:
      output: true

defaults:
  - scope:
      path: ""
      type: "col_tags"
    values:
      permalink: /tags/:slug/
      layout: tag_page
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /posts/:title/
      layout: post

projects:
  - name: netease-music-java
    description: 网易云音乐 Java API
    link: https://github.com/c0ldcat/netease-music-java
    image: /images/netease-music.svg
  - name: hackwlb-server
    description: 本站开源哦
    link: https://github.com/c0ldcat/hackwlb-server
    image: /c0ldcat.png
  - name: bio-font-z
    description: 生物笔记符号字体
    link: https://github.com/c0ldcat/bio-font-z
    image: /images/bio-font-z.svg

social:
  - service: github
    username: c0ldcat
    link: https://github.com/c0ldcat
  - service: mail
    username: firez199984@gmail.com
    link: mailto:firez199984@gmail.com

sass:
  style:            :compressed

gems:
  - jekyll-seo-tag

exclude:
  - "*.dot"
  - ".*"
  - "Gemfile"
  - "deploy.sh"
  - "deploy_key"
  - "deploy_key.enc"
