name:               "c0ldcat's blog"
description:        "ä¸€ä¸ªèœé¸¡å…¨æ ˆå¤§ä¸€ç‹—"

url:                "//blog.c0ldcat.ml"
author:             "c0ldcat"

baseurl:            ""

markdown:           kramdown

timezone:           Asia/Shanghai

nav:
  - name:           "ğŸ–Šï¸"
    href:           "/posts"
  - name:           "ğŸˆ"
    href:           "/projects"
  - name:           "ğŸ”–"
    href:           "/tags"
  - name:           "â¤ï¸"
    href:           "/love"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /posts/:title/
      layout: post

projects:
  - name: Netease Music Java
    description: ç½‘æ˜“äº‘éŸ³ä¹ Java API
    link: https://github.com/c0ldcat/netease-music-java
    image: /images/netease-music.svg
  - name: Scale JPG
    description: ä¸€æ­¥è§£å†³å›¾ç‰‡å¤§å°æ ¼å¼é™åˆ¶é—®é¢˜
    link: https://github.com/c0ldcat/scale-jpg
    image: /images/scale-jpg.svg
  - name: Z Uploader
    description: Group uploader, æ”¶æ–‡ä»¶ä¸“ç”¨
    link: https://github.com/c0ldcat/z-uploader
    image: /images/z-uploader.svg
  - name: Hackwlb Server
    description: æœ¬ç«™å¼€æºå“¦
    link: https://github.com/c0ldcat/hackwlb-server
    image: /images/c0ldcat.svg
  - name: Red Music
    description: Bluetooth MP3 with Netease Music
    link: https://github.com/c0ldcat/red-music
    image: /images/red-music.svg
  - name: KR Home Protocol
    description: ç‚¹å¯¹ç‚¹å¼æ™ºèƒ½å®¶å…·åè®®
    link: "#"
    image: /images/kmp.svg
  - name: RopeZ
    description: å‰å®³çš„çº¿é˜µLEDè·³ç»³
    link: "#"
    image: /images/rope-z.svg
  - name: Pet Camera
    description: Intel IOT 2015! è¶…å¥½ç”¨çš„å® ç‰©æ™ºèƒ½æ‹ç…§ç¥å™¨
    link: https://github.com/c0ldcat/Pet-Camera
    image: /images/pet-camera.svg
  - name: iTool MagicQT Box with LBox Extra
    description: æ•¬é€å»çš„å­¦ä¹ æœºæ—¶ä»£
    link: https://github.com/c0ldcat/Noah-NP2300-LBox
    image: /images/lbox.svg

social:
  - service: github
    username: c0ldcat
    link: https://github.com/c0ldcat
  - service: mail
    username: firez199984@gmail.com
    link: mailto:firez199984@gmail.com

background: /images/background.png

sass:
    sass_dir:         _sass
    style:            :compressed

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

tags_paginate: 10
tags_paginate_path: "/tags/:num"

paginate: 10
paginate_path: "/posts/:num"

plugins:
  - jekyll-seo-tag
  - jekyll/tagging
  - jekyll-paginate

exclude:
  - "*.dot"
  - ".*"
  - "Gemfile"
  - "genGemfile.sh"
  - "deploy.sh"
  - "deploy_key"
  - "deploy_key.enc"
  - "vendor"
